Taureon/aps-plus-plus

- server/modules/live/entity.js
> borderless fix

- public/app.js
- public/lib/util.js
- server/lib/definitions.js
- server/modules/global.js
- server/modules/live/entity.js
- server/modules/network/sockets.js
- server/modules/setup/mockups.js
- Added HSL adjustment for entities and barrels
- Upgrades now show the proper color
- Added rainbowclone as a demonstration
- Minimap rendering still doesn't work lol
> COLORS!!!!!!

- server/modules/live/entity.js
my god what the hell is this bugfix it's so stupid
> destroy oldest child working

- run.sh
Just to save linux users from typing an extra command lol
> Add run.sh file for linux users :)

- public/app.js
- server/lib/definitions.js
- server/modules/live/entity.js
> fixed deco properties for non-firing barrels

- server/modules/live/entity.js
Fixed undefined this.colorUnboxed
> Moved define

- run.sh
Change run.sh from "node server/index.js" to "node server/index"
> Tiny change

- server/index.js
- server/modules/definitions/groups/tanks.js
- server/modules/live/entity.js
Assembler tank was made for [Discord Challenge](https://discord.com/channels/1004907608018264094/1140351024327049226/1140366668904796270)
> Assembler tank

- server/modules/live/entity.js
> Entity don't die when collides with wall type fix

- public/app.js
- public/lib/socketInit.js
- server/modules/live/entity.js
Self-explanatory
(stupid code)
> Fix all entities being counted as kills

- public/app.js
- public/lib/util.js
- server/modules/definitions/groups/bosses.js
- server/modules/definitions/groups/dev.js
- server/modules/definitions/groups/tanks.js
- server/modules/live/entity.js
- server/modules/setup/mockups.js
> Upgrade Panel Colors, Glow Effect, and (Somewhat Working) Turret Vulnerability 

- server/modules/definitions/groups/bosses.js
- server/modules/definitions/groups/dev.js
> add my devboss

- public/app.js
ideally we'd preload images when mockups are loaded but im too lazy for that atm
> SHAPE now accepts image URLS

- server/index.js
- server/modules/definitions/groups/bosses.js
- server/modules/definitions/groups/dev.js
- server/modules/definitions/groups/generics.js
- server/modules/live/entity.js
Added `ON` replacing `ON_FIRE`
Added `gun.properties.IDENTIFIER`
```js
ON: [
{
action: "fire",
execute: ({ body, gun }) => {
if (gun.identifier != 'mainGun') return
// So we know that the gun were dealing with is the gun we want
// can be seen below
}
},
{
action: "death",
execute: ({ body, killers, killTools }) => {} // parameters will change depening on what action it was
}
]
GUNS: [{
POSITION: {},
PROPERTIES: { IDENTIFIER: 'mainGun' }
}]
> On property

- server/modules/definitions/groups/bosses.js
- server/modules/definitions/groups/misc.js
- server/permissions.js
> Fix Kronos Missile x Shiny Sentries

- server/modules/network/otherServers.json
> Umbrarras new link

- README.md
> Add addons link

- public/lib/socketInit.js
just added a break so it doesnt show error in the console and doesnt break the grid
> fix the info packet.

- README.md
its server list from ranar the wratfull, i have permission from him on arras coding hub [here](https://ptb.discord.com/channels/1004907608018264094/1183874571498164355/1209252010776600666)
> Add server list link

- server/modules/definitions/combined.js
- server/modules/global.js
- server/modules/network/sockets.js
Its just for addon devs that want their addon dont crash when another addon doesnt exist
> Some changes

- server/modules/definitions/addons/labyFood.js
- server/modules/definitions/groups/food.js
**[Laby polygon incorrect score scaling upon death](https://github.com/Taureon/aps-plus-plus/issues/158) bug report**
- Fix for Laby polygon incorrect score scaling upon death
> Laby food buff

- server/modules/definitions/groups/tanks.js
- server/modules/live/entity.js
i finally did it, basically all this does is fix desmos movement and nerf quadruplex. :D
> Fixesss (desmos edition) (REAL FIX THIS TIME IM NOT KIDDING)

- public/app.js
- public/lib/canvas.js
yup, its intentional, i know. i know, im super epic 😎
> Mobile Crosshair and Joystick fix

- server/modules/definitions/groups/bosses.js
- server/modules/definitions/groups/dev.js
> Helena dev boss

- server/modules/live/entity.js
This caused some random infinite range with some custom tanks
> Minor spelling mistake
